Feature(reviews): Add hasSpoiler Checkbox
plotwist-app/plotwist pull request #240
Opened 2024-10-22 17:02 UTC by Vicentesan

# This PR introduces a new feature that allows users to mark a review as containing spoilers. The following changes were made:

## "Contains Spoiler" Checkbox:

- Added a checkbox to the review form that users can select if their review contains spoilers.

## Database Schema Update:

- New column contains_spoiler added to the reviews table, as a boolean field (default: false). - Still need to create the migration file

## Updated Create Review Function:

- Modified the function responsible for creating a review to include the contains_spoiler flag.
Now, when a review is created, the contains_spoiler value from the form is properly saved in the database.

## Changes:

- Frontend:
  - Added the "Contains Spoiler" checkbox to the review submission form.
  - Adjusted the review display logic to handle spoiler reviews accordingly.
  
- Backend/Functions:
  - Modified create review function to accept and process the contains_spoiler flag.

- Database:
  - Added the "contain_spoilers" field in the schema
  
## Screenshots:
Before:
![image](https://github.com/user-attachments/assets/611baea1-e83c-48f4-85ee-8473823c74ab)

After:
![image](https://github.com/user-attachments/assets/bc7979ab-7532-44f8-86b4-f31263ed8841)

# Testing:
 - [ ❌] Tested the review submission process with and without the spoiler checkbox checked.
 - [ ❌] Verified the database correctly stores and retrieves the contains_spoiler field.
 - [ ❌] Checked the frontend displays reviews with spoilers appropriately.
 - [ ❌] Tested the review creation function to ensure it properly saves the contains_spoiler flag.
 
 I'll do all these tests when I properly migrate the dev database
 
 ## Todo:
- Add modal warning when the user attempts to publish the review without checking the checkbox to make sure he didn't forgot about it
 
Related Issues:
https://github.com/plotwist-app/plotwist/issues/234

2024-10-24 01:22 UTC, eulixir commented on apps/web/src/services/api/reviews/create-review.ts
> +  contain_spoilers,
Eu trocaria para `has_spoilers`, o que acha?. E pode deixar o campo camelCase, o prisma lida com essa conversão.

2024-10-24 01:32 UTC, Vicentesan commented on apps/web/src/services/api/reviews/create-review.ts
> +  contain_spoilers,
alterado no commit a seguir

2024-10-24 03:49 UTC, eulixir requested changes
Do you think it's a good idea to put a blur when the review is marked as hasSpoiler == true?

2024-10-24 03:49 UTC, eulixir commented on apps/web/src/services/api/reviews/create-review.ts
> +    hasSpoilers,
```suggestion
    has_spoiler: hasSpoilers,
```

2024-10-24 03:49 UTC, eulixir commented on apps/web/src/services/api/reviews/create-review.ts
> +/* eslint-disable camelcase */
```suggestion
```

2024-10-24 03:49 UTC, eulixir commented on debug.log
> +[1023/222729.906:ERROR:crashpad_client_win.cc(810)] not connected
```suggestion
```

avoid commit the debug log to github

2024-10-24 14:45 UTC, Vicentesan commented on apps/web/src/services/api/reviews/create-review.ts
> +    hasSpoilers,
changed in the next commit

2024-10-24 14:45 UTC, Vicentesan commented on apps/web/src/services/api/reviews/create-review.ts
> +/* eslint-disable camelcase */
removed in the next commit

2024-10-24 14:45 UTC, Vicentesan commented on debug.log
> +[1023/222729.906:ERROR:crashpad_client_win.cc(810)] not connected
removed in the next commit

2024-10-24 14:46 UTC, Vicentesan commented
> Do you think it's a good idea to put a blur when the review is marked as hasSpoiler == true?

Yes, I do think its a good Idea. I will do it now!

2024-10-29 20:11 UTC, Vicentesan commented
@eulixir Ready for merge. Last review please?

2024-10-31 12:04 UTC, eulixir approved these changes
LGTM, waiting for @lui7henrique review to merge

2024-10-31 13:13 UTC, merged